// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmX6IqtFi_CSMXazzuHK_BpVu3opRtHAA',
    appId: '1:990945662476:web:66d60115648371cb1dc029',
    messagingSenderId: '990945662476',
    projectId: 'chatappfirebase2-1df27',
    authDomain: 'chatappfirebase2-1df27.firebaseapp.com',
    storageBucket: 'chatappfirebase2-1df27.appspot.com',
    measurementId: 'G-C5BYS6JGZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4qloUR_IfSokcrlJD8yzVWMTxq-U4ziQ',
    appId: '1:990945662476:android:db6d0c1203d627fb1dc029',
    messagingSenderId: '990945662476',
    projectId: 'chatappfirebase2-1df27',
    storageBucket: 'chatappfirebase2-1df27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfn3eqYMOIQUu0FXNSl-DyViMYkXwRWEs',
    appId: '1:990945662476:ios:836471f8daae0dd91dc029',
    messagingSenderId: '990945662476',
    projectId: 'chatappfirebase2-1df27',
    storageBucket: 'chatappfirebase2-1df27.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfn3eqYMOIQUu0FXNSl-DyViMYkXwRWEs',
    appId: '1:990945662476:ios:1a1b0823da2d073f1dc029',
    messagingSenderId: '990945662476',
    projectId: 'chatappfirebase2-1df27',
    storageBucket: 'chatappfirebase2-1df27.appspot.com',
    iosBundleId: 'com.example.chatappFirebase.RunnerTests',
  );
}
